### ISSUE TITLE
livereload crashing with errors in console

### ISSUE THREAD

**Issue by mjasnikovs** [livereload/livereload-js#43]
/usr/local/lib/node_modules/livereloadx/node_modules/ws/lib/WebSocket.js:214
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/livereloadx/node_modules/ws/lib/WebSocket.js:214:16)
    at /usr/local/lib/node_modules/livereloadx/lib/websocket.js:21:14
    at Array.forEach (native)
    at Object.WebSocketHandler.send (/usr/local/lib/node_modules/livereloadx/lib/websocket.js:20:18)
    at Object.Server.notifyFileChange (/usr/local/lib/node_modules/livereloadx/lib/server.js:108:22)
    at Watcher.<anonymous> (/usr/local/lib/node_modules/livereloadx/lib/server.js:119:16)
    at Watcher.EventEmitter.emit (events.js:95:17)
    at /usr/local/lib/node_modules/livereloadx/lib/watcher.js:33:12
    at Array.forEach (native)
    at FSMonitor.<anonymous> (/usr/local/lib/node_modules/livereloadx/lib/watcher.js:32:52)

Any help? Need additional information?

**Comment by smhg** [comment]
This seems to be an error message from a [different library](https://github.com/nitoyon/livereloadx). Start by reporting your issue there, but don't hesitate to include this project should it be related.
